version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates every week
    schedule:
      interval: "weekly"
    # Limit to 5 open pull requests at any time
    open-pull-requests-limit: 5
    # Add labels on pull requests
    labels:
      - "npm"
      - "dependencies"
      - "security"
    # Add reviewers
    reviewers:
      - "pskinnertech"
    # Specify target branch
    target-branch: "main"
    # Allow up-to-date branches to be rebased
    rebase-strategy: "auto"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*" 